In [95]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [96]:
df_train = pd.read_csv('/kaggle/CarPrice/train.csv')
df_test = pd.read_csv('/kaggle/CarPrice/test.csv')
df_sub = pd.read_csv('/kaggle/CarPrice/sample_submission.csv')

In [97]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1642 entries, 0 to 1641
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         1642 non-null   object
 1   year          1642 non-null   int64
 2   motor_type    1642 non-null   object
 3   running       1642 non-null   object
 4   wheel         1642 non-null   object
 5   color         1642 non-null   object
 6   type          1642 non-null   object
 7   status        1642 non-null   object
 8   motor_volume  1642 non-null   float64
 9   price         1642 non-null   int64
dtypes: float64(1), int64(2), object(7)
memory usage: 128.4+ KB

In [98]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 411 entries, 0 to 410
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            411 non-null    int64
 1   model         411 non-null    object
 2   year          411 non-null    int64
 3   motor_type    411 non-null    object
 4   running       411 non-null    object
 5   wheel         411 non-null    object
 6   color         411 non-null    object
 7   type          411 non-null    object
 8   status        411 non-null    object
 9   motor_volume  411 non-null    float64
dtypes: float64(1), int64(2), object(7)
memory usage: 32.2+ KB

In [99]:
df_train['wheel'].value_counts()

wheel
left    1642
Name: count, dtype: int64

In [100]:
df_test['wheel'].value_counts()

wheel
left     409
right      2
Name: count, dtype: int64

In [101]:
df_train = df_train.drop('wheel', axis=1)
df_test = df_test.drop('wheel', axis=1)

In [102]:
df_test = df_test.drop('Id', axis=1)

In [103]:
df_train['motor_type'].value_counts()

motor_type
petrol            1420
gas                165
petrol and gas      54
diesel               2
hybrid               1
Name: count, dtype: int64

In [104]:
df_test['motor_type'].value_counts()

motor_type
petrol            356
gas                36
petrol and gas     19
Name: count, dtype: int64

In [105]:
df_train[df_train['motor_type'].isin(['diesel', 'hybrid'])]

,model,year,motor_type,running,color,type,status,motor_volume,price
429,mercedes-benz,2022,diesel,50 km,gray,pickup,excellent,2.0,15750
1446,mercedes-benz,2008,diesel,190000 miles,black,sedan,excellent,2.1,10500
1505,hyundai,2021,hybrid,12000 km,white,sedan,excellent,1.6,23400

In [106]:
df_train['motor_type'] = df_train['motor_type'].replace(['diesel', 'hybrid'], 'petrol')
df_test['motor_type'] = df_test['motor_type'].replace(['diesel', 'hybrid'], 'petrol')

In [107]:
df_train['running'].value_counts()

running
300000  km       19
70000  miles     18
60000  miles     17
120000  km       16
65000  miles     15
                 ..
51500  miles      1
153000  miles     1
26780  km         1
89000  miles      1
6500  km          1
Name: count, Length: 643, dtype: int64

In [108]:
df_test['running'].value_counts()

running
85000  miles    8
120000  km      6
200000  km      5
55000  miles    5
27000  miles    5
               ..
249000  km      1
41800  miles    1
101000  km      1
33400  km       1
218000  km      1
Name: count, Length: 270, dtype: int64

In [109]:
df_train['running'] = df_train['running'].apply(lambda x: x.split(' ')[0])
df_test['running'] = df_test['running'].apply(lambda x: x.split(' ')[0])

In [ ]:
df_train['running'] = df_train['running'].astype(int)
df_test['running'] = df_test['running'].astype(int)

In [110]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1642 entries, 0 to 1641
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         1642 non-null   object
 1   year          1642 non-null   int64
 2   motor_type    1642 non-null   object
 3   running       1642 non-null   object
 4   color         1642 non-null   object
 5   type          1642 non-null   object
 6   status        1642 non-null   object
 7   motor_volume  1642 non-null   float64
 8   price         1642 non-null   int64
dtypes: float64(1), int64(2), object(6)
memory usage: 115.6+ KB

In [111]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 411 entries, 0 to 410
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         411 non-null    object
 1   year          411 non-null    int64
 2   motor_type    411 non-null    object
 3   running       411 non-null    object
 4   color         411 non-null    object
 5   type          411 non-null    object
 6   status        411 non-null    object
 7   motor_volume  411 non-null    float64
dtypes: float64(1), int64(1), object(6)
memory usage: 25.8+ KB

In [112]:
df_train['color'].value_counts()

color
black      541
white      407
silver     223
gray       189
blue       141
red         47
other       30
cherry      20
green       10
brown       10
golden       6
beige        5
orange       5
clove        3
skyblue      2
purple       2
pink         1
Name: count, dtype: int64

In [113]:
df_test['color'].value_counts()

color
black      131
white       96
silver      61
gray        55
blue        30
red         11
other        7
cherry       7
green        5
orange       3
brown        2
skyblue      1
clove        1
beige        1
Name: count, dtype: int64

In [114]:
set(df_test['color']) - set(df_train['color'])

set()

In [115]:
set(df_train['color']) - set(df_test['color'])

{'golden', 'pink', 'purple'}

In [116]:
df_train['type'].value_counts()

type
sedan                1276
suv                   301
Universal              37
hatchback              15
Coupe                  11
pickup                  1
minivan / minibus       1
Name: count, dtype: int64

In [117]:
df_test['type'].value_counts()

type
sedan        320
suv           67
Universal     19
Coupe          4
hatchback      1
Name: count, dtype: int64

In [118]:
df_train['type'] = df_train['type'].replace(['pickup', 'minivan / minibus'], 'Universal')

In [119]:
df_train['type'].value_counts()

type
sedan        1276
suv           301
Universal      39
hatchback      15
Coupe          11
Name: count, dtype: int64

In [120]:
df_train['status'].value_counts()

status
excellent    1200
good          334
normal         58
crashed        29
new            21
Name: count, dtype: int64

In [121]:
df_test['status'].value_counts()

status
excellent    304
good          82
normal        12
crashed        7
new            6
Name: count, dtype: int64

In [128]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1642 entries, 0 to 1641
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         1642 non-null   object
 1   year          1642 non-null   int64
 2   motor_type    1642 non-null   object
 3   running       1642 non-null   int64
 4   color         1642 non-null   object
 5   type          1642 non-null   object
 6   status        1642 non-null   object
 7   motor_volume  1642 non-null   float64
 8   price         1642 non-null   int64
dtypes: float64(1), int64(3), object(5)
memory usage: 115.6+ KB

In [125]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 411 entries, 0 to 410
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         411 non-null    object
 1   year          411 non-null    int64
 2   motor_type    411 non-null    object
 3   running       411 non-null    object
 4   color         411 non-null    object
 5   type          411 non-null    object
 6   status        411 non-null    object
 7   motor_volume  411 non-null    float64
dtypes: float64(1), int64(1), object(6)
memory usage: 25.8+ KB

In [126]:
df_train['running'].value_counts()

running
70000     33
100000    25
60000     25
120000    25
300000    19
          ..
12500      1
18211      1
277000     1
30200      1
44500      1
Name: count, Length: 502, dtype: int64

In [129]:
X_train = df_train.drop('price', axis=1)
y_train = df_train['price']
X_test = df_test.copy()

In [130]:
X_train = pd.get_dummies(X_train, drop_first=True, dtype=int)
X_test = pd.get_dummies(X_test, drop_first=True, dtype=int)

In [131]:
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

In [135]:
from sklearn.tree import DecisionTreeRegressor

In [136]:
from sklearn.model_selection import GridSearchCV

In [137]:
model = DecisionTreeRegressor()

In [138]:
param_grid = {
   'criterion': ['squared_error', 'absolute_error'],
   'max_depth': [5, 10, 15, 20, None],
   'min_samples_split': [2, 10, 20],
   'min_samples_leaf': [1, 5, 15]
}

In [140]:
final_model = GridSearchCV(model, param_grid, cv=5, verbose = 3)

In [142]:
y_train

0       24500
1       25500
2       11700
3       12000
4       26000
        ...
1637    12400
1638    16500
1639    19500
1640    19500
1641    28500
Name: price, Length: 1642, dtype: int64

In [143]:
final_model.fit(X_train, y_train)

Fitting 5 folds for each of 90 candidates, totalling 450 fits
[CV 1/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=2;, score=0.655 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=2;, score=0.669 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=2;, score=0.679 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=2;, score=0.686 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=2;, score=0.618 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=10;, score=0.651 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=10;, score=0.672 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=10;, score=0.687 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=10;, score=0.686 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=10;, score=0.636 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=20;, score=0.655 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=20;, score=0.673 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=20;, score=0.692 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=20;, score=0.718 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=5, min_samples_leaf=1, min_samples_split=20;, score=0.664 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=2;, score=0.596 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=2;, score=0.648 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=2;, score=0.801 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=2;, score=0.731 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=2;, score=0.589 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=10;, score=0.596 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=10;, score=0.648 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=10;, score=0.801 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=10;, score=0.731 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=10;, score=0.589 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=20;, score=0.675 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=20;, score=0.657 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=20;, score=0.786 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=20;, score=0.748 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=5, min_samples_leaf=5, min_samples_split=20;, score=0.634 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=2;, score=0.664 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=2;, score=0.655 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=2;, score=0.757 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=2;, score=0.734 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=2;, score=0.616 total time=   0.1s
[CV 1/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=10;, score=0.664 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=10;, score=0.655 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=10;, score=0.757 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=10;, score=0.734 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=10;, score=0.616 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=20;, score=0.664 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=20;, score=0.655 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=20;, score=0.757 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=20;, score=0.734 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=5, min_samples_leaf=15, min_samples_split=20;, score=0.616 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=2;, score=0.650 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=2;, score=0.499 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=2;, score=0.633 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=2;, score=0.569 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=2;, score=0.652 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=10;, score=0.605 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=10;, score=0.590 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=10;, score=0.639 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=10;, score=0.698 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=10;, score=0.654 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=20;, score=0.701 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=20;, score=0.682 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=20;, score=0.640 total time=   0.1s
[CV 4/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=20;, score=0.745 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=10, min_samples_leaf=1, min_samples_split=20;, score=0.703 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=2;, score=0.623 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=2;, score=0.663 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=2;, score=0.783 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=2;, score=0.755 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=2;, score=0.658 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=10;, score=0.623 total time=   0.1s
[CV 2/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=10;, score=0.663 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=10;, score=0.783 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=10;, score=0.755 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=10;, score=0.658 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=20;, score=0.706 total time=   0.1s
[CV 2/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=20;, score=0.660 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=20;, score=0.782 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=20;, score=0.779 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=10, min_samples_leaf=5, min_samples_split=20;, score=0.689 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=2;, score=0.697 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=2;, score=0.663 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=2;, score=0.755 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=2;, score=0.749 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=2;, score=0.695 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=10;, score=0.697 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=10;, score=0.663 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=10;, score=0.755 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=10;, score=0.749 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=10;, score=0.695 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=20;, score=0.697 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=20;, score=0.663 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=20;, score=0.755 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=20;, score=0.749 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=10, min_samples_leaf=15, min_samples_split=20;, score=0.695 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=2;, score=0.575 total time=   0.1s
[CV 2/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=2;, score=0.510 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=2;, score=0.616 total time=   0.1s
[CV 4/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=2;, score=0.528 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=2;, score=0.633 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=10;, score=0.642 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=10;, score=0.596 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=10;, score=0.641 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=10;, score=0.685 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=10;, score=0.649 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=20;, score=0.644 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=20;, score=0.679 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=20;, score=0.643 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=20;, score=0.731 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=15, min_samples_leaf=1, min_samples_split=20;, score=0.701 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=2;, score=0.616 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=2;, score=0.663 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=2;, score=0.779 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=2;, score=0.745 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=2;, score=0.636 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=10;, score=0.616 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=10;, score=0.663 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=10;, score=0.779 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=10;, score=0.745 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=10;, score=0.641 total time=   0.1s
[CV 1/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=20;, score=0.702 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=20;, score=0.660 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=20;, score=0.780 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=20;, score=0.772 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=15, min_samples_leaf=5, min_samples_split=20;, score=0.683 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=2;, score=0.696 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=2;, score=0.663 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=2;, score=0.755 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=2;, score=0.749 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=2;, score=0.693 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=10;, score=0.696 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=10;, score=0.663 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=10;, score=0.755 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=10;, score=0.749 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=10;, score=0.693 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=20;, score=0.696 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=20;, score=0.663 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=20;, score=0.755 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=20;, score=0.749 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=15, min_samples_leaf=15, min_samples_split=20;, score=0.693 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=2;, score=0.598 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=2;, score=0.477 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=2;, score=0.570 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=2;, score=0.595 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=2;, score=0.630 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=10;, score=0.601 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=10;, score=0.594 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=10;, score=0.640 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=10;, score=0.683 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=10;, score=0.647 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=20;, score=0.695 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=20;, score=0.678 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=20;, score=0.640 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=20;, score=0.730 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=20, min_samples_leaf=1, min_samples_split=20;, score=0.706 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=20, min_samples_leaf=5, min_samples_split=2;, score=0.616 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=20, min_samples_leaf=5, min_samples_split=2;, score=0.662 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=20, min_samples_leaf=5, min_samples_split=2;, score=0.778 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=20, min_samples_leaf=5, min_samples_split=2;, score=0.745 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_depth=20, min_samples_leaf=5, min_samples_split=2;, score=0.641 total time=   0.1s
[CV 1/5] END criterion=squared_error, max_depth=20, min_samples_leaf=5, min_samples_split=10;, score=0.616 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=20, min_samples_leaf=5, min_samples_split=10;, score=0.662 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=20, min_samples_leaf=5, min_samples_split=10;, score=0.778 total time=   0.0s

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_depth': [5, 10, 15, 20, None],
                         'min_samples_leaf': [1, 5, 15],
                         'min_samples_split': [2, 10, 20]},
             verbose=3)

In [144]:
y_pred = final_model.predict(X_test)

In [145]:
df_sub['price'] = y_pred

In [146]:
df_sub.to_csv('sub.csv', index=False, index_label=False)

**Score: 2016.0097**

**---------------------------------------------------------------------------------------------------------**

**RANDOM FOREST REGRESSOR**

In [167]:
X_train = df_train.drop('price', axis=1)
y_train = df_train['price']
X_test = df_test.copy()

In [168]:
X_train = pd.get_dummies(X_train, drop_first=True, dtype=int)
X_test = pd.get_dummies(X_test, drop_first=True, dtype=int)

In [169]:
from sklearn.ensemble import RandomForestRegressor

In [170]:
from sklearn.model_selection import GridSearchCV

In [171]:
model = RandomForestRegressor()

In [172]:
params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 15, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 5],
    'max_features': [1.0, 'sqrt']
}

In [175]:
rf_final_model = GridSearchCV(model, params, cv=5, verbose=3)

In [176]:
rf_final_model.fit(X_train, y_train)

Fitting 5 folds for each of 216 candidates, totalling 1080 fits
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=100;, score=0.737 total time=   0.6s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=100;, score=0.645 total time=   0.5s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=100;, score=0.776 total time=   0.5s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=100;, score=0.767 total time=   0.5s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=100;, score=0.762 total time=   0.5s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=200;, score=0.732 total time=   1.0s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=200;, score=0.647 total time=   1.0s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=200;, score=0.785 total time=   1.0s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=200;, score=0.764 total time=   1.3s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=200;, score=0.760 total time=   1.5s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=300;, score=0.728 total time=   1.6s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=300;, score=0.644 total time=   1.6s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=300;, score=0.788 total time=   1.4s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=300;, score=0.762 total time=   1.5s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=2, n_estimators=300;, score=0.757 total time=   1.6s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=100;, score=0.728 total time=   0.5s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=100;, score=0.655 total time=   0.4s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=100;, score=0.787 total time=   0.6s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=100;, score=0.766 total time=   0.5s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=100;, score=0.753 total time=   0.5s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=200;, score=0.730 total time=   1.2s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=200;, score=0.651 total time=   1.4s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=200;, score=0.791 total time=   1.1s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=200;, score=0.770 total time=   1.1s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=200;, score=0.751 total time=   1.0s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=300;, score=0.734 total time=   1.6s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=300;, score=0.651 total time=   1.5s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=300;, score=0.782 total time=   1.6s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=300;, score=0.771 total time=   1.5s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=5, n_estimators=300;, score=0.757 total time=   1.9s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=100;, score=0.736 total time=   0.7s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=100;, score=0.666 total time=   0.7s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=100;, score=0.795 total time=   0.7s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=100;, score=0.779 total time=   0.5s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=100;, score=0.758 total time=   0.5s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=200;, score=0.734 total time=   0.9s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=200;, score=0.663 total time=   1.1s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=200;, score=0.784 total time=   0.8s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=200;, score=0.784 total time=   0.9s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=200;, score=0.751 total time=   1.0s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=300;, score=0.730 total time=   1.6s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=300;, score=0.666 total time=   1.6s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=300;, score=0.789 total time=   2.0s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=300;, score=0.786 total time=   2.0s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=1, min_samples_split=10, n_estimators=300;, score=0.752 total time=   1.6s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.714 total time=   0.6s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.675 total time=   0.6s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.813 total time=   0.6s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.806 total time=   0.6s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.717 total time=   0.5s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=200;, score=0.713 total time=   1.4s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=200;, score=0.659 total time=   1.2s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=200;, score=0.809 total time=   1.1s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=200;, score=0.800 total time=   1.2s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=200;, score=0.701 total time=   2.0s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=300;, score=0.712 total time=   2.4s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=300;, score=0.670 total time=   1.8s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=300;, score=0.814 total time=   1.4s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=300;, score=0.801 total time=   1.5s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=2, n_estimators=300;, score=0.699 total time=   1.9s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.713 total time=   0.7s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.658 total time=   0.6s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.813 total time=   0.6s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.795 total time=   0.5s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.698 total time=   0.6s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=200;, score=0.718 total time=   1.1s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=200;, score=0.674 total time=   1.4s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=200;, score=0.812 total time=   1.3s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=200;, score=0.801 total time=   0.9s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=200;, score=0.705 total time=   1.0s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=300;, score=0.709 total time=   1.6s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=300;, score=0.663 total time=   1.3s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=300;, score=0.815 total time=   1.4s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=300;, score=0.801 total time=   1.4s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=5, n_estimators=300;, score=0.699 total time=   1.3s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.723 total time=   0.4s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.681 total time=   0.4s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.817 total time=   0.7s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.803 total time=   0.7s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.727 total time=   0.6s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=200;, score=0.722 total time=   1.2s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=200;, score=0.676 total time=   0.8s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=200;, score=0.819 total time=   0.8s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=200;, score=0.801 total time=   0.9s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=200;, score=0.724 total time=   0.9s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=300;, score=0.723 total time=   1.3s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=300;, score=0.676 total time=   1.2s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=300;, score=0.819 total time=   1.2s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=300;, score=0.805 total time=   1.2s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=2, min_samples_split=10, n_estimators=300;, score=0.723 total time=   1.2s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.725 total time=   0.6s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.682 total time=   0.6s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.822 total time=   0.6s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.798 total time=   0.7s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.719 total time=   0.6s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=200;, score=0.721 total time=   0.8s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=200;, score=0.684 total time=   0.8s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=200;, score=0.824 total time=   0.8s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=200;, score=0.800 total time=   0.8s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=200;, score=0.715 total time=   0.8s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=300;, score=0.722 total time=   1.2s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=300;, score=0.682 total time=   1.2s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=300;, score=0.824 total time=   1.2s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=300;, score=0.798 total time=   1.1s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=2, n_estimators=300;, score=0.709 total time=   1.2s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.720 total time=   0.5s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.682 total time=   0.6s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.824 total time=   0.6s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.800 total time=   0.6s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.710 total time=   0.6s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=200;, score=0.723 total time=   0.8s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=200;, score=0.681 total time=   0.8s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=200;, score=0.822 total time=   0.8s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=200;, score=0.798 total time=   0.8s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=200;, score=0.708 total time=   0.8s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=300;, score=0.723 total time=   1.2s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=300;, score=0.679 total time=   1.3s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=300;, score=0.827 total time=   1.2s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=300;, score=0.798 total time=   1.1s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=5, n_estimators=300;, score=0.711 total time=   1.1s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.724 total time=   0.5s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.682 total time=   0.6s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.822 total time=   0.6s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.798 total time=   0.6s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.716 total time=   0.6s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=200;, score=0.719 total time=   0.8s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=200;, score=0.679 total time=   0.7s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=200;, score=0.824 total time=   0.8s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=200;, score=0.801 total time=   0.8s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=200;, score=0.707 total time=   0.8s
[CV 1/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=300;, score=0.720 total time=   1.1s
[CV 2/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=300;, score=0.682 total time=   1.2s
[CV 3/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=300;, score=0.825 total time=   1.2s
[CV 4/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=300;, score=0.799 total time=   1.1s
[CV 5/5] END max_depth=10, max_features=1.0, min_samples_leaf=5, min_samples_split=10, n_estimators=300;, score=0.717 total time=   1.1s
[CV 1/5] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100;, score=0.686 total time=   0.2s
[CV 2/5] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100;, score=0.561 total time=   0.2s
[CV 3/5] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100;, score=0.744 total time=   0.3s
[CV 4/5] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100;, score=0.720 total time=   0.3s
[CV 5/5] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100;, score=0.643 total time=   0.4s
[CV 1/5] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200;, score=0.690 total time=   0.7s
[CV 2/5] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200;, score=0.568 total time=   0.7s
[CV 3/5] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200;, score=0.760 total time=   0.6s
[CV 4/5] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200;, score=0.725 total time=   0.4s
[CV 5/5] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200;, score=0.640 total time=   0.4s
[CV 1/5] END max_depth=10, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=300;, score=0.687 total time=   0.6s

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid={'max_depth': [10, 15, 20, None],
                         'max_features': [1.0, 'sqrt'],
                         'min_samples_leaf': [1, 2, 5],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]},
             verbose=3)

In [178]:
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

In [181]:
rf_y_pred = rf_final_model.predict(X_test)

In [182]:
df_sub['price'] = rf_y_pred

In [183]:
df_sub.to_csv('rf_sub.csv', index=False, index_label=False)

**Score: 1891.7341**